-- Rebuilds `events` as the wide load-testing table: the original columns, key and
-- rows, plus about a hundred columns of every native type, JSON and geometry
-- included. Run through dev/load.sh; the default seeds never do this.

SET client_min_messages = warning;
DROP TABLE IF EXISTS events;
DROP TYPE IF EXISTS event_severity, event_stage;

CREATE TYPE event_severity AS ENUM ('debug', 'info', 'notice', 'warning', 'error', 'critical');
CREATE TYPE event_stage AS ENUM ('received', 'validated', 'enriched', 'stored', 'archived');

CREATE TABLE events (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    account_id bigint NOT NULL,
    kind text NOT NULL,
    amount numeric(12, 2) NOT NULL,
    occurred_at timestamptz NOT NULL,
    quantity smallint NOT NULL,
    priority smallint,
    http_status smallint NOT NULL,
    retries integer NOT NULL,
    session_seq integer NOT NULL,
    duration_ms integer NOT NULL,
    shard_no integer,
    bytes_in bigint NOT NULL,
    bytes_out bigint,
    trace_id bigint NOT NULL,
    price numeric(10, 4) NOT NULL,
    tax numeric(8, 3),
    discount numeric(5, 2) NOT NULL,
    total numeric(14, 2) NOT NULL,
    fx_rate numeric(12, 8) NOT NULL,
    big_numeric numeric(30, 10) NOT NULL,
    balance_after numeric(12, 2),
    cost money,
    score real NOT NULL,
    temp_c real,
    load_avg real NOT NULL,
    latency_s double precision NOT NULL,
    ratio double precision,
    weight_kg double precision NOT NULL,
    cpu_pct double precision NOT NULL,
    is_test boolean NOT NULL,
    is_mobile boolean NOT NULL,
    is_retry boolean,
    consent boolean,
    flagged boolean NOT NULL,
    archived boolean NOT NULL,
    country char(2) NOT NULL,
    currency char(3) NOT NULL,
    locale varchar(8) NOT NULL,
    channel varchar(32) NOT NULL,
    device text NOT NULL,
    browser text NOT NULL,
    os text NOT NULL,
    campaign text,
    referrer text,
    city text NOT NULL,
    sku varchar(16) NOT NULL,
    status text NOT NULL,
    user_agent varchar(120) NOT NULL,
    tag varchar(20),
    title text NOT NULL,
    description text NOT NULL,
    notes text,
    stack_trace text,
    severity event_severity NOT NULL,
    stage event_stage,
    event_date date NOT NULL,
    due_date date,
    event_time time NOT NULL,
    time_tz timetz NOT NULL,
    created_at timestamp NOT NULL,
    updated_at timestamptz NOT NULL,
    processed_at timestamptz,
    expires_at timestamp,
    window_start timestamptz NOT NULL,
    window_end timestamptz NOT NULL,
    elapsed interval NOT NULL,
    ttl interval,
    event_uuid uuid NOT NULL,
    session_uuid uuid NOT NULL,
    parent_uuid uuid,
    client_ip inet NOT NULL,
    server_ip inet NOT NULL,
    subnet cidr NOT NULL,
    mac macaddr,
    payload_hash bytea NOT NULL,
    signature bytea,
    thumbnail bytea NOT NULL,
    permissions bit(8) NOT NULL,
    bitmap varbit,
    tags text[] NOT NULL,
    scores integer[] NOT NULL,
    prices numeric[],
    flags boolean[],
    related_ids uuid[],
    grid integer[][],
    qty_range int4range NOT NULL,
    active_during tstzrange,
    envelope xml,
    search_vector tsvector NOT NULL,
    props_small jsonb NOT NULL,
    props_nested jsonb NOT NULL,
    props_large jsonb NOT NULL,
    meta_small json NOT NULL,
    meta_nested json,
    location geometry(Point, 4326) NOT NULL,
    route geometry(LineString, 4326),
    area geometry(Polygon, 4326),
    native_point point NOT NULL,
    bounds box,
    reach circle,
    outline polygon,
    valid_dates daterange NOT NULL,
    price_band numrange,
    id_span int8range NOT NULL,
    query tsquery,
    mac8 macaddr8
);

INSERT INTO events (
    account_id, kind, amount, occurred_at,
    quantity, priority, http_status, retries, session_seq, duration_ms, shard_no,
    bytes_in, bytes_out, trace_id,
    price, tax, discount, total, fx_rate, big_numeric, balance_after, cost,
    score, temp_c, load_avg, latency_s, ratio, weight_kg, cpu_pct,
    is_test, is_mobile, is_retry, consent, flagged, archived,
    country, currency, locale, channel, device, browser, os, campaign, referrer,
    city, sku, status, user_agent, tag,
    title, description, notes, stack_trace,
    severity, stage,
    event_date, due_date, event_time, time_tz, created_at, updated_at, processed_at,
    expires_at, window_start, window_end, elapsed, ttl,
    event_uuid, session_uuid, parent_uuid, client_ip, server_ip, subnet, mac,
    payload_hash, signature, thumbnail, permissions, bitmap,
    tags, scores, prices, flags, related_ids, grid, qty_range, active_during,
    envelope, search_vector,
    props_small, props_nested, props_large, meta_small, meta_nested,
    location, route, area,
    native_point, bounds, reach, outline, valid_dates, price_band, id_span, query, mac8
)
SELECT (n % 6) + 1,
       (ARRAY['click', 'view', 'purchase', 'refund', 'signup', 'churn'])[(n % 6) + 1],
       round((n % 100000)::numeric / 100, 2),
       timestamptz '2024-01-01 00:00:00+00' + (n * interval '1 second'),
       (n % 1000)::smallint,
       CASE WHEN n % 7 = 0 THEN NULL ELSE (n % 5)::smallint END,
       (ARRAY[200, 201, 204, 301, 400, 404, 500])[(n % 7) + 1]::smallint,
       n % 4,
       n % 100000,
       (n * 37) % 30000,
       CASE WHEN n % 10 = 0 THEN NULL ELSE n % 64 END,
       (n::bigint * 7919) % 10000000,
       CASE WHEN n % 9 = 0 THEN NULL ELSE (n::bigint * 104729) % 50000000 END,
       n::bigint * 2654435761 % 9000000000000000,
       round(((n % 50000) / 7.0)::numeric, 4),
       CASE WHEN n % 8 = 0 THEN NULL ELSE round(((n % 2000) / 13.0)::numeric, 3) END,
       round((n % 30)::numeric / 2, 2),
       round(((n % 700000) / 3.0)::numeric, 2),
       round((0.5 + (n % 1000) / 1000.0)::numeric, 8),
       (n::numeric * 123456789.0123456789) % 10000000000000000000,
       CASE WHEN n % 11 = 0 THEN NULL ELSE round((n % 90000)::numeric / 3, 2) END,
       CASE WHEN n % 12 = 0 THEN NULL ELSE ((n % 50000) / 100.0)::numeric::money END,
       (n % 1000) / 7.0,
       CASE WHEN n % 6 = 0 THEN NULL ELSE (-20 + (n % 600) / 10.0) END,
       (n % 400) / 100.0,
       (n % 20000) / 1000.0,
       CASE WHEN n % 13 = 0 THEN NULL ELSE (n % 1000) / 1000.0 END,
       40 + (n % 500) / 10.0,
       (n % 10000) / 100.0,
       n % 20 = 0,
       n % 3 = 0,
       CASE WHEN n % 5 = 0 THEN NULL ELSE n % 4 = 0 END,
       CASE WHEN n % 4 = 0 THEN NULL ELSE n % 3 <> 0 END,
       n % 50 = 0,
       n % 17 = 0,
       (ARRAY['US', 'GB', 'DE', 'FR', 'JP', 'BR', 'IN', 'CA'])[(n % 8) + 1],
       (ARRAY['USD', 'GBP', 'EUR', 'JPY'])[(n % 4) + 1],
       (ARRAY['en-US', 'en-GB', 'de-DE', 'fr-FR', 'ja-JP'])[(n % 5) + 1],
       (ARRAY['web', 'ios', 'android', 'api', 'email'])[(n % 5) + 1],
       (ARRAY['desktop', 'phone', 'tablet', 'watch'])[(n % 4) + 1],
       (ARRAY['Firefox', 'Chrome', 'Safari', 'Edge'])[(n % 4) + 1],
       (ARRAY['macOS', 'Windows', 'Linux', 'iOS', 'Android'])[(n % 5) + 1],
       CASE WHEN n % 3 = 0 THEN NULL ELSE 'campaign-' || (n % 40) END,
       CASE WHEN n % 4 = 0 THEN NULL ELSE 'https://example.com/ref/' || (n % 300) END,
       (ARRAY['Berlin', 'Tokyo', 'Austin', 'Lyon', 'Recife', 'Pune', 'Leeds', 'Toronto'])[(n % 8) + 1],
       'SKU-' || lpad((n % 10000)::text, 6, '0'),
       (ARRAY['ok', 'pending', 'failed', 'skipped'])[(n % 4) + 1],
       'Mozilla/5.0 (compatible; dbdelve-load/' || (n % 10) || '.0; build ' || (n % 1000) || ') AppleWebKit/537.36',
       CASE WHEN n % 6 = 0 THEN NULL ELSE 'tag-' || (n % 100) END,
       'Event ' || n || ' for account ' || ((n % 6) + 1),
       'Synthetic load-test event number ' || n || '. ' || repeat('The quick brown fox jumps over the lazy dog. ', 4),
       CASE WHEN n % 2 = 0 THEN NULL ELSE repeat('Operator note ' || n || ': follow up with the customer. ', 8) END,
       CASE WHEN n % 20 = 0 THEN repeat('at com.example.Handler.process(Handler.java:' || (n % 900) || ')' || E'\n', 12) END,
       (ARRAY['debug', 'info', 'notice', 'warning', 'error', 'critical'])[(n % 6) + 1]::event_severity,
       CASE WHEN n % 8 = 0 THEN NULL ELSE (ARRAY['received', 'validated', 'enriched', 'stored', 'archived'])[(n % 5) + 1]::event_stage END,
       date '2024-01-01' + (n % 1000),
       CASE WHEN n % 5 = 0 THEN NULL ELSE date '2024-06-01' + (n % 400) END,
       time '00:00:00' + (n % 86400) * interval '1 second',
       ((time '00:00:00' + (n % 86400) * interval '1 second') || '+00')::timetz,
       timestamp '2024-01-01 00:00:00' + (n * interval '1 second'),
       timestamptz '2024-01-01 00:00:00+00' + (n * interval '1 second') + interval '90 seconds',
       CASE WHEN n % 4 = 0 THEN NULL ELSE timestamptz '2024-01-01 00:00:00+00' + (n * interval '1 second') + interval '3 minutes' END,
       CASE WHEN n % 6 = 0 THEN NULL ELSE timestamp '2025-01-01 00:00:00' + ((n % 100000) * interval '1 minute') END,
       timestamptz '2024-01-01 00:00:00+00' + ((n - n % 3600) * interval '1 second'),
       timestamptz '2024-01-01 00:00:00+00' + ((n - n % 3600 + 3600) * interval '1 second'),
       make_interval(hours => n % 48, mins => n % 60, secs => (n % 600) / 7.0),
       CASE WHEN n % 3 = 0 THEN NULL ELSE make_interval(days => n % 30) END,
       md5('event' || n)::uuid,
       md5('session' || (n / 20))::uuid,
       CASE WHEN n % 4 = 0 THEN NULL ELSE md5('event' || (n / 2))::uuid END,
       ('10.' || (n % 256) || '.' || ((n / 256) % 256) || '.' || (n % 250 + 1))::inet,
       ('192.168.' || (n % 16) || '.' || (n % 250 + 1))::inet,
       ('10.' || (n % 256) || '.0.0/16')::cidr,
       CASE WHEN n % 5 = 0 THEN NULL ELSE ('02:00:' || substr(md5(n::text), 1, 2) || ':' || substr(md5(n::text), 3, 2) || ':' || substr(md5(n::text), 5, 2) || ':' || substr(md5(n::text), 7, 2))::macaddr END,
       decode(md5(n::text), 'hex'),
       CASE WHEN n % 3 = 0 THEN NULL ELSE decode(md5(n::text) || md5((n + 1)::text), 'hex') END,
       decode(repeat(md5((n % 1000)::text), 4), 'hex'),
       (n % 256)::bit(8),
       CASE WHEN n % 7 = 0 THEN NULL ELSE (n % 1024)::bit(10)::varbit END,
       ARRAY['tag-' || (n % 10), 'group-' || (n % 7), 'region-' || (n % 5)],
       ARRAY[n % 10, n % 100, n % 1000],
       CASE WHEN n % 4 = 0 THEN NULL ELSE ARRAY[(n % 100) / 4.0, (n % 50) / 3.0]::numeric[] END,
       CASE WHEN n % 6 = 0 THEN NULL ELSE ARRAY[n % 2 = 0, n % 3 = 0, n % 5 = 0] END,
       CASE WHEN n % 5 = 0 THEN NULL ELSE ARRAY[md5('a' || n)::uuid, md5('b' || n)::uuid] END,
       CASE WHEN n % 9 = 0 THEN NULL ELSE ARRAY[[n % 10, n % 7], [n % 5, n % 3]] END,
       int4range(n % 100, n % 100 + 1 + n % 50),
       CASE WHEN n % 5 = 0 THEN NULL ELSE tstzrange(
           timestamptz '2024-01-01 00:00:00+00' + (n * interval '1 second'),
           timestamptz '2024-01-01 00:00:00+00' + (n * interval '1 second') + interval '1 hour') END,
       CASE WHEN n % 10 = 0 THEN NULL ELSE ('<event id="' || n || '"><kind>' || (n % 6) || '</kind></event>')::xml END,
       to_tsvector('simple', 'event ' || n || ' account ' || ((n % 6) + 1) || ' batch ' || (n % 100)),
       jsonb_build_object('source', 'load', 'ok', n % 5 <> 0, 'attempt', n % 4, 'ratio', round((n % 100) / 100.0, 2), 'note', CASE WHEN n % 3 = 0 THEN NULL ELSE 'n' || n END),
       jsonb_build_object(
           'user', jsonb_build_object('id', n % 5000, 'name', 'user-' || (n % 5000),
                                      'roles', jsonb_build_array('viewer', 'editor', 'admin')),
           'request', jsonb_build_object('method', (ARRAY['GET', 'POST', 'PUT', 'DELETE'])[(n % 4) + 1],
                                         'path', '/api/v1/items/' || (n % 900),
                                         'headers', jsonb_build_object('accept', 'application/json', 'x-trace', md5(n::text))),
           'items', jsonb_build_array(
               jsonb_build_object('sku', 'SKU-' || (n % 100), 'qty', n % 5 + 1, 'price', round((n % 1000) / 10.0, 1)),
               jsonb_build_object('sku', 'SKU-' || (n % 77), 'qty', n % 3 + 1, 'price', round((n % 500) / 10.0, 1)),
               jsonb_build_object('sku', 'SKU-' || (n % 31), 'qty', 1, 'price', round((n % 250) / 10.0, 1))),
           'tags', jsonb_build_array('a' || (n % 10), 'b' || (n % 7), 'c' || (n % 5))),
       jsonb_build_object(
           'id', n,
           'summary', jsonb_build_object('count', 10, 'total', round((n % 100000) / 100.0, 2), 'currency', 'USD'),
           'entries', (SELECT jsonb_agg(jsonb_build_object(
                           'index', i,
                           'name', 'entry-' || i || '-' || (n % 1000),
                           'value', round(((n * i) % 10000) / 10.0, 1),
                           'enabled', (n + i) % 2 = 0,
                           'labels', jsonb_build_array('l' || i, 'm' || (i % 3)),
                           'coords', jsonb_build_array((n + i) % 180, (n * i) % 90)))
                       FROM generate_series(1, 10) AS i)),
       jsonb_build_object('v', 1, 'region', 'r' || (n % 5), 'seq', n)::json,
       CASE WHEN n % 4 = 0 THEN NULL ELSE jsonb_build_object(
           'client', jsonb_build_object('name', 'web', 'version', '1.' || (n % 20) || '.' || (n % 9),
                                        'features', jsonb_build_array('a', 'b', 'c')),
           'samples', jsonb_build_array(n % 100, n % 50, n % 25, n % 10),
           'geo', jsonb_build_object('lat', round((n % 1700) / 10.0 - 85, 1), 'lon', round((n % 3500) / 10.0 - 175, 1)))::json END,
       ST_SetSRID(ST_MakePoint((n % 3600) / 10.0 - 180, (n % 1700) / 10.0 - 85), 4326),
       CASE WHEN n % 6 = 0 THEN NULL ELSE ST_SetSRID(ST_MakeLine(ARRAY[
           ST_MakePoint((n % 3500) / 10.0 - 175, (n % 1600) / 10.0 - 80),
           ST_MakePoint((n % 3500) / 10.0 - 174, (n % 1600) / 10.0 - 79),
           ST_MakePoint((n % 3500) / 10.0 - 172, (n % 1600) / 10.0 - 79.5)]), 4326) END,
       CASE WHEN n % 4 = 0 THEN NULL ELSE ST_SetSRID(ST_MakeEnvelope(
           (n % 3500) / 10.0 - 175, (n % 1600) / 10.0 - 80,
           (n % 3500) / 10.0 - 174, (n % 1600) / 10.0 - 79), 4326) END,
       point((n % 3600) / 10.0 - 180, (n % 1700) / 10.0 - 85),
       CASE WHEN n % 4 = 0 THEN NULL ELSE box(point(n % 100, n % 50), point(n % 100 + 5, n % 50 + 3)) END,
       CASE WHEN n % 5 = 0 THEN NULL ELSE circle(point(n % 100, n % 50), 1 + n % 9) END,
       CASE WHEN n % 6 = 0 THEN NULL ELSE polygon(box(point(n % 100, n % 50), point(n % 100 + 2, n % 50 + 2))) END,
       daterange(date '2024-01-01' + (n % 1000), date '2024-01-01' + (n % 1000) + 1 + n % 90),
       CASE WHEN n % 7 = 0 THEN NULL ELSE numrange((n % 500) / 10.0, (n % 500) / 10.0 + 25) END,
       int8range(n::bigint * 1000, n::bigint * 1000 + 999),
       CASE WHEN n % 3 = 0 THEN NULL ELSE to_tsquery('simple', 'event & account' || ((n % 6) + 1)) END,
       CASE WHEN n % 5 = 0 THEN NULL ELSE ('02:00:00:00:' || substr(md5(n::text), 1, 2) || ':' || substr(md5(n::text), 3, 2) || ':' || substr(md5(n::text), 5, 2) || ':' || substr(md5(n::text), 7, 2))::macaddr8 END
FROM generate_series(1, @ROWS@) AS g(n);

